[build]
  publish = "dist/smart-calendar"
  command = "npm install && npx ng build --configuration=production"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"