[build]
  publish = "dist/smart-calendar"
  command = "npm install --include=dev && npx ng build --configuration=production"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
