[build]
  publish = "dist/smart-calendar"
  command = "npm install && ng build --configuration=production"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"